/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 25/08/2020 09:14:52
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            37000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            16000000
#define MX_HSE_VALUE                            24000000
#define MX_MSI_VALUE                            2097000
#define MX_PLLCLKFreq_Value                     32000000
#define MX_SYSCLKFreq_VALUE                     32000000
#define MX_HCLKFreq_Value                       32000000
#define MX_FCLKCortexFreq_Value                 32000000
#define MX_AHBFreq_Value                        32000000
#define MX_APB1Freq_Value                       32000000
#define MX_APB2Freq_Value                       32000000
#define MX_ADCFreq_Value                        16000000
#define MX_LCDFreq_Value                        37000
#define MX_RTCFreq_Value                        37000
#define MX_RTCHSEDivFreq_Value                  12000000
#define MX_TimerFreq_Value                      32000000
#define MX_VCOOutputFreq_Value                  64000000
#define MX_WatchDogFreq_Value                   37000
#define MX_MCOPinFreq_Value                     32000000
#define MX_VCOInputFreq_Value                   16000000

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

/* Pin PB7 */
#define MX_PB7_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PB7_Pin                              PB7
#define MX_PB7_GPIOx                            GPIOB
#define MX_PB7_PinState                         GPIO_PIN_RESET
#define MX_PB7_GPIO_PuPd                        GPIO_NOPULL
#define MX_PB7_GPIO_Pin                         GPIO_PIN_7
#define MX_PB7_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PA0-WKUP1 */
#define MX_PA0_WKUP1_Pin                        PA0_WKUP1
#define MX_PA0_WKUP1_GPIOx                      GPIOA
#define MX_PA0_WKUP1_GPIO_PuPd                  GPIO_NOPULL
#define MX_PA0_WKUP1_GPIO_Pin                   GPIO_PIN_0
#define MX_PA0_WKUP1_GPIO_Mode                  GPIO_MODE_INPUT

/* Pin PB6 */
#define MX_PB6_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PB6_Pin                              PB6
#define MX_PB6_GPIOx                            GPIOB
#define MX_PB6_PinState                         GPIO_PIN_RESET
#define MX_PB6_GPIO_PuPd                        GPIO_NOPULL
#define MX_PB6_GPIO_Pin                         GPIO_PIN_6
#define MX_PB6_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

#endif  /* __MX_DEVICE_H */
